name: minimal_chef
description: "A minimal cooking app, written in Flutter"
publish_to: 'none'

version: 0.1.0+beta4

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.9
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  google_sign_in: ^6.2.0
  google_sign_in_web: ^0.12.4
  image_picker: ^1.0.4
  html: ^0.15.4
  morphable_shape: ^2.0.0
  http: ^1.5.0
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_dotenv: ^5.1.0
  args: ^2.4.2
  crypto: ^3.0.3
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-Variable.ttf
