baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Zest Documentation'

[menu]
[[menu.main]]
  name = "User Docs"
  url = "/user/"
  weight = 10
[[menu.main]]
  name = "Developer Docs"
  url = "/developer/"
  weight = 20

[params]
  description = "Documentation for Zest App"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"